# Generated by Django 5.2.4 on 2025-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_uploads/"),
        ),
    ]
