# Generated by Django 5.2.4 on 2025-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_heading",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
