# Generated by Django 5.2.4 on 2025-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_file_heading_alter_message_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="is_sticker",
            field=models.BooleanField(default=False),
        ),
    ]
