# Generated by Django 5.2.4 on 2025-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_message_gif_url_message_is_sticker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
